<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../../form/NewForm.vue'
export default {

    props: ['id'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Salary Group Manager",
                formName : "SalaryGroupForm",
                model : "SalaryGroup",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'salary_group_name', val : 'Salary Group', type : 'text' },
                    { key : 'display', val : 'Display', type : 'text' },
                    { key : 'payment_type', val : 'Payment Type', type : 'text' },
                    { key : 'salary_amount', val : 'Salary Amount', type : 'text' },
                ],
                elements : [

                    {
                        label : 'Display',
                        name : 'display',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Display', value : '' },
                            { key : 'Show', value : 'Show' },
                            { key : 'Hide', value : 'Hide' },
                        ],
                        placeholder : 'Please Select Display',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Display',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Payment Type',
                        name : 'payment_type',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Payment Type', value : '' },
                            { key : 'Hourly', value : 'Hourly' },
                            { key : 'Monthly', value : 'Monthly' },
                        ],
                        placeholder : 'Please Select Payment Type',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Payment Type',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Salary Group Name',
                        name : 'salary_group_name',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Salary Group Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Salary Group Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Description',
                        name : 'description',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Description',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-9 col-lg-9 col-xl-9 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Description',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Working Minutes per Day',
                        name : 'working_minutes_per_day',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Working Minutes per Day',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Working Minutes per Day',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Salary Amount',
                        name : 'salary_amount',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Salary Amount',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Salary Amount',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Basic Salary',
                        name : 'basic',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Basic Salary',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Basic Salary',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'House Rent Allowance',
                        name : 'houserent',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter House Rent Allowance',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter House Rent Allowance',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Dearness Allowance',
                        name : 'dearness',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Dearness Allowance',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Dearness Allowance',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Conveyance Allowance',
                        name : 'conveyance',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Conveyance Allowance',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Conveyance Allowance',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Travelling Allowance',
                        name : 'travelling',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Travelling Allowance',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Travelling Allowance',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Employee PF Share',
                        name : 'employee_pf',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Employee PF Share',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Employee PF Share',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Employer PF Share',
                        name : 'employer_pf',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Employer PF Share',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Employer PF Share',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Professional Tax',
                        name : 'professional_tax',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Professional Tax',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Professional Tax',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'ESIC Amount',
                        name : 'esic',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter ESIC Amount',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter ESIC Amount',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Overtime per Hour',
                        name : 'otperhr',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Overtime per Hour',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Overtime per Hour',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Bonus',
                        name : 'bonus',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Bonus',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Bonus',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                ],
            },
        }
    },

    methods : {

        change(e){
            /* console.log(e.target.value); */
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
    },

    mounted() {
    },

}
</script>
