<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../../form/NewForm.vue'
export default {

    props: ['id', 'branches', 'classrooms', 'slots'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Batch Manager",
                formName : "BatchForm",
                model : "Batch",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'batch_name', val : 'Batch Name', type : 'text' },
                    { key : 'effective_from', val : 'From', type : 'text' },
                    { key : 'effective_till', val : 'To', type : 'text' },
                ],
                elements : [

                    {
                        label : 'Branch ID',
                        name : 'branch_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.branches,
                        placeholder : 'Please Select Branch ID',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Branch ID',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Classroom ID',
                        name : 'classroom_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.classrooms,
                        placeholder : 'Please Select Classroom ID',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Classroom ID',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Classroom Type',
                        name : 'classroom_type',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Classroom Type', value : '' },
                            { key : 'Fixed', value : 'Fixed' },
                            { key : 'Moving', value : 'Moving' },
                        ],
                        placeholder : 'Please Select Classroom Type',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Classroom Type',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Batch Type',
                        name : 'batch_type',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Batch Type', value : '' },
                            { key : 'Daily', value : 'Daily' },
                            { key : 'Staggered', value : 'Staggered' },
                        ],
                        placeholder : 'Please Select Batch Type',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Batch Type',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Batch Name',
                        name : 'batch_name',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Batch Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Batch Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Effective From',
                        name : 'effective_from',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Effective From',
                        type : 'date',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Effective From',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Effective Till',
                        name : 'effective_till',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Effective Till',
                        type : 'date',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Effective Till',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'No of Sessions',
                        name : 'sessions',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter No of Sessions',
                        type : 'text',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter No of Sessions',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Monday',
                        name : 'mon_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Monday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Monday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Tuesday',
                        name : 'tue_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Tuesday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Tuesday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Wednesday',
                        name : 'wed_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Wednesday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Wednesday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Thursday',
                        name : 'thu_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Thursday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Thursday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Firday',
                        name : 'fri_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Firday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Firday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Saturday',
                        name : 'sat_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Saturday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Saturday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sunday',
                        name : 'sun_slots',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : this.slots,
                        placeholder : 'Enter Sunday',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Sunday',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                ],
            },
        }
    },

    methods : {

        change(e){
            /* console.log(e.target.value); */
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
    },

    mounted() {
    },

}
</script>
