<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData" @OnChange="change($event)"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../../form/NewForm.vue'
export default {

    props: ['id'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Student Manager",
                formName : "StudentForm",
                model : "Student",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'fname', val : 'First Name', type : 'text' },
                    { key : 'mname', val : 'Middle Name', type : 'text' },
                    { key : 'lname', val : 'Last Name', type : 'text' },
                    { key : 'gender', val : 'Gender', type : 'text' },
                    { key : 'dob', val : 'Date of Birth', type : 'text' },
                    { key : 'city', val : 'City', type : 'text' },
                    { key : 'email', val : 'Email', type : 'text' },
                    { key : 'contact_number', val : 'Mobile', type : 'text' },
                    { key : 'parents_number', val : 'Parents Mobile', type : 'text' },
                ],
                elements : [
                    
                    {
                        label : 'First Name',
                        name : 'fname',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter First Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter First Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Middle name',
                        name : 'mname',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Middle name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Middle name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Last Name',
                        name : 'lname',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Last Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Last Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Gender',
                        name : 'gender',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Gender', value : '' },
                            { key : 'Male', value : 'Male' },
                            { key : 'Female', value : 'Female' },
                            { key : 'Other', value : 'Other' },
                        ],
                        placeholder : 'Please Select Gender',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Gender',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Date of Birth',
                        name : 'dob',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Date of Birth',
                        type : 'date',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Date of Birth',
                        error : '',
                        isError : false,
                        readonly : false,
                    },



                    {
                        label : 'Fathers Name',
                        name : 'fathersname',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Fathers Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Fathers Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Mothers Name',
                        name : 'mothersname',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Mothers Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Mothers Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Address',
                        name : 'address',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Address',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Address',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'City',
                        name : 'city',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter City',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter City',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Pincode',
                        name : 'pincode',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Pincode',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Pincode',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'State',
                        name : 'state',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter State',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter State',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Country',
                        name : 'country',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Country',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Country',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Permanant Address is Same',
                        name : 'same_address',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            {key: "Yes my permanent address is same", value: "Yes"}
                        ],
                        placeholder : 'Enter Permanant Address is Same',
                        type : 'checkbox',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Permanant Address is Same',
                        error : '',
                        isError : false,
                        readonly : false,
                    },


                    {
                        label : 'Permanent Address',
                        name : 'permanent_address',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Address',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Address',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Permanent City',
                        name : 'permanent_city',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter City',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter City',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Permanent Pincode',
                        name : 'permanent_pincode',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Pincode',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Pincode',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Permanent State',
                        name : 'permanent_state',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter State',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter State',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Permanent Country',
                        name : 'permanent_country',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Country',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Country',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Email',
                        name : 'email',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Email',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Email',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Contact Number',
                        name : 'contact_number',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Contact Number',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Contact Number',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Parents Number',
                        name : 'parents_number',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Parents Number',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Parents Number',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Instagram ID',
                        name : 'instagram_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Instagram ID',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Instagram ID',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Facebook ID',
                        name : 'facebook_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Facebook ID',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Facebook ID',
                        error : '',
                        isError : false,
                        readonly : false,
                    },


                ],
            },
        }
    },

    methods : {

        change(e){
            
            if(e.target.name == "same_address") {
                if(e.target.checked){
                    this.formData.elements[13].value = this.formData.elements[7].value;
                    this.formData.elements[14].value = this.formData.elements[8].value;
                    this.formData.elements[15].value = this.formData.elements[9].value;
                    this.formData.elements[16].value = this.formData.elements[10].value;
                    this.formData.elements[17].value = this.formData.elements[11].value;
                } else {
                    this.formData.elements[13].value = null;
                    this.formData.elements[14].value = null;
                    this.formData.elements[15].value = null;
                    this.formData.elements[16].value = null;
                    this.formData.elements[17].value = null;
                }
            }
            if(this.formData.elements[12].value == "Yes"){
                alert("Praise the Lord");
            }
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
        
    },

    mounted() {
    },

}
</script>
