<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../../form/NewForm.vue'
export default {

    props: ['id'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Staff Manager",
                formName : "StaffForm",
                model : "Staff",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'employee_name', val : 'Name', type : 'text' },
                    { key : 'dob', val : 'Date of Birth', type : 'text' },
                    { key : 'gender', val : 'Gender', type : 'text' },
                    { key : 'blood_group', val : 'Blood Group', type : 'text' },
                    { key : 'aadhar', val : 'Aadhar', type : 'text' },
                    { key : 'pan', val : 'PAN', type : 'text' },
                    { key : 'city', val : 'City', type : 'text' },
                    { key : 'joining', val : 'Joining Date', type : 'text' },
                    { key : 'exit', val : 'Exit Date', type : 'text' },
                    { key : 'photo', val : 'Photo', type : 'image' },

                ],
                elements : [

                    {
                        label : 'Employee Name',
                        name : 'employee_name',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Employee Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Employee Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Gender',
                        name : 'gender',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Gender', value : '' },
                            { key : 'Male', value : 'Male' },
                            { key : 'Female', value : 'Female' },
                            { key : 'Other', value : 'Other' },
                        ],
                        placeholder : 'Please Select Gender',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Gender',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Blood Group',
                        name : 'blood_group',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Blood Group', value : '' },
                            { key : 'O+', value : 'O+' },
                            { key : 'O-', value : 'O-' },
                            { key : 'A+', value : 'A+' },
                            { key : 'A-', value : 'A-' },
                            { key : 'B+', value : 'B+' },
                            { key : 'B-', value : 'B-' },
                            { key : 'AB+', value : 'AB+' },
                            { key : 'AB-', value : 'AB-' },
                            { key : 'Other', value : 'Other' },
                        ],
                        placeholder : 'Please Select Blood Group',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Blood Group',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Date of Birth',
                        name : 'dob',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Date of Birth',
                        type : 'date',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Date of Birth',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Joining Date',
                        name : 'joining',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Joining Date',
                        type : 'date',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Joining Date',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Exit Date',
                        name : 'exit',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Exit Date',
                        type : 'date',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Exit Date',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Aadhar Card Number',
                        name : 'aadhar',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Aadhar Card Number',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Aadhar Card Number',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'PAN Card Number',
                        name : 'pan',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter PAN Card Number',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter PAN Card Number',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Address',
                        name : 'address',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Address',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Address',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'City',
                        name : 'city',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter City',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter City',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Pincode',
                        name : 'pincode',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Pincode',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Pincode',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'State',
                        name : 'state',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter State',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter State',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Country',
                        name : 'country',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Country',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Country',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Contact Number',
                        name : 'contact_number',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Contact Number',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Contact Number',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Email',
                        name : 'email',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Email',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Email',
                        error : '',
                        isError : false,
                        readonly : false,
                    },


                    {
                        label : 'Photograph',
                        name : 'photo',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Photograph',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Photograph is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },


                ],
            },
        }
    },

    methods : {

        change(e){
            /* console.log(e.target.value); */
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
    },

    mounted() {
    },

}
</script>
